steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: validate
    args:
      - endpoints
      - services
      - deploy
      - openapi-functions.yaml
      - --validate-only
  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy
    waitFor:
      - validate
    args:
      - endpoints
      - services
      - deploy
      - openapi-functions.yaml
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor:
      - deploy
    args:
      - beta
      - run
      - deploy
      - esp
      - --image=gcr.io/endpoints-release/endpoints-runtime-serverless:1.40.0
      - --allow-unauthenticated
      - --platform=managed
      - --region=us-central1
