steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: validate
    args:
      - endpoints
      - services
      - deploy
      - openapi.yaml
      - --validate-only
      
  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy
    # waitFor:
    #   - validate
    args:
      - endpoints
      - services
      - deploy
      - openapi.yaml

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor:
      - deploy
    args:
      - beta
      - run
      - deploy
      - esp
      - --image=gcr.io/endpoints-release/endpoints-runtime-serverless:1
      - --allow-unauthenticated
      - --platform=managed
      - --region=us-east1
      - --update-env-vars=ENDPOINTS_SERVICE_NAME=esp-fjwomrdjca-ue.a.run.app
