swagger: "2.0"
info:
  title: Bookit Backend API
  description: Sample API on Cloud Endpoints with a Google Cloud Functions backend
  version: 0.0.1
host: esp-vllmtwjp2a-uc.a.run.app
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
definitions:
  Profile:
    type: object
    properties:
      birthday:
        type: string
      firstName:
        type: string
      gender:
        type: integer
      isProvider:
        type: boolean
      isSocial:
        type: boolean
      lastName:
        type: string
      phoneNumber:
        type: string
      uid:
        type: string
    required:
      - uid
      - firstName
      - lastName
      - isProvider
      - isSocial
      - phoneNumber
  Message:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      technicalError:
        type: string
paths:
  /profile:
    post:
      summary: Create a new User Profile
      operationId: profileCreate
      x-google-backend:
        address: https://us-central1-sweng-581-capstone.cloudfunctions.net/profile-create
      parameters:
        - in: body
          name: profile
          description: Details of the profile to be created
          schema:
            $ref: "#/definitions/Profile"
      responses:
        201:
          description: Profile is created
        400:
          description: Request is malformed or profile already exists
          schema:
            $ref: "#/definitions/Message"
    get:
      summary: Query for a user profile
      operationId: profileQuery
      x-google-backend:
        address: https://us-central1-sweng-581-capstone.cloudfunctions.net/profile-query
      parameters:
        - in: query
          name: profileId
          type: string
          description: Profile ID to be queried. Typically the UID of the user
      responses:
        200:
          description: Profile was found
          schema:
            $ref: "#/definitions/Profile"
        400:
          description: Invalid request typically profileId is missing
        404:
          description: Profile doesn't exist
